feat: Add subgraph checks

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -52,3 +52,30 @@ jobs:
       - name: Unexpected success
         if: steps.test.outputs.error == ''
         run: echo "Succeeded unexpectedly" && exit 1
+  subgraph:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check GraphQL
+        id: test
+        uses: ./
+        with:
+          endpoint: https://graphql-test.up.railway.app/subgraph
+          subgraph: true
+  not_a_subgraph:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check GraphQL
+        id: test
+        continue-on-error: true
+        uses: ./
+        with:
+          endpoint: https://graphql-test.up.railway.app/graphql
+          subgraph: true
+      - name: Verify failure
+        if: steps.test.outputs.error != ''
+        run: echo "Failed as expected"
+      - name: Unexpected success
+        if: steps.test.outputs.error == ''
+        run: echo "Succeeded unexpectedly" && exit 1
